import fs from "fs";
import path from "path";

import PDFDocument from "pdfkit/js/pdfkit.standalone";

import { GeneratePDFInput } from "./pdf.types";

import {
  addBulletList,
  addSectionTitle,
} from "./pdf.utils";

export async function generatePDF(
  data: GeneratePDFInput,
): Promise<string> {
  return new Promise((resolve, reject) => {
    try {
      const {
        companyName,
        website,
        email,
        insights,
      } = data;

      // Create output directory
      const outputDir = path.join(
        process.cwd(),
        "src",
        "generated",
        "pdfs",
      );

      if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, {
          recursive: true,
        });
      }

      // Generate filename
      const fileName = `${companyName
        .replace(/\s+/g, "_")
        .toLowerCase()}_report.pdf`;

      const filePath = path.join(outputDir, fileName);

      // Create PDF document
      const doc = new PDFDocument({
        margin: 50,
      });

      // Create stream
      const stream = fs.createWriteStream(filePath);

      doc.pipe(stream);

      // Cover title
      doc
        .fontSize(28)
        .fillColor("#111827")
        .text("AI Business Intelligence Report", {
          align: "center",
        });

      doc.moveDown(2);

      // Company name
      doc
        .fontSize(20)
        .fillColor("#2563EB")
        .text(companyName, {
          align: "center",
        });

      doc.moveDown();

      // Contact info
      doc
        .fontSize(12)
        .fillColor("#6B7280")
        .text(`Website: ${website}`, {
          align: "center",
        });

      doc.text(`Email: ${email}`, {
        align: "center",
      });

      doc.moveDown(5);

      // Company Overview
      addSectionTitle(doc, "Company Overview");

      doc
        .fontSize(12)
        .fillColor("#374151")
        .text(insights.companyOverview, {
          lineGap: 6,
        });

      // Strengths
      addSectionTitle(doc, "Business Strengths");

      addBulletList(doc, insights.strengths);

      // Weaknesses
      addSectionTitle(doc, "Weaknesses");

      addBulletList(doc, insights.weaknesses);

      // Growth Opportunities
      addSectionTitle(doc, "Growth Opportunities");

      addBulletList(doc, insights.growthOpportunities);

      // Automation Suggestions
      addSectionTitle(
        doc,
        "AI Automation Suggestions",
      );

      addBulletList(
        doc,
        insights.automationSuggestions,
      );

      // Marketing
      addSectionTitle(doc, "Marketing Suggestions");

      addBulletList(
        doc,
        insights.marketingSuggestions,
      );

      // SEO
      addSectionTitle(doc, "SEO Improvements");

      addBulletList(doc, insights.seoImprovements);

      // Footer
      doc.moveDown(4);

      doc
        .fontSize(10)
        .fillColor("#9CA3AF")
        .text(
          "Generated by AI Automation System",
          {
            align: "center",
          },
        );

      // Register listeners BEFORE end
      stream.on("finish", () => {
        resolve(filePath);
      });

      stream.on("error", (error) => {
        reject(error);
      });

      // Finalize PDF
      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}